### ISSUE TITLE
Make it docker hub

### ISSUE THREAD

**Issue by glats** [Cheloide/wls1036#1]
Please docker hubirzed the image to acces easily by downloading from the store

**Comment by cheloide** [comment]
As per [ Oracle Technology Network License Agreement](https://www.oracle.com/technetwork/licenses/standard-license-152015.html) I can't do the following: "make the Programs available in any manner to any third party", because of that you have to download the installers with an Oracle account and build the image. If you find an official source of wls1036 and jdk1.6 installers where you are allowed to download them without logging in, I could upload the image.
